### PR TITLE
logout shouldnt clear credentials

### PR DESCRIPTION
**Pull request by soycode**
For consideration - while working on https://github.com/freedomjs/freedom-social-email I used this provider for reference, and think that perhaps we should (a) not clear credentials on logout (that's what clearCredentials is for) and less importantly (b) clear credentials by setting to null (since that's the "default state"). Thoughts/feedback welcome, whatever we decide here I'll mimic in other the email provider/elsewhere.

### CODE REVIEW

**Comment by dborkan** [comment]
Won't this change mean that calling .logout() then .login(..) again will attempt to log back in as the previous user (assuming their credentials haven't expired)?  Is that the behavior we want?

BTW this won't affect uProxy because we create a new freedom[socialProvider] object for every new login.

**Comment by soycode** [comment]
Yes it would mean that, unless the client calls `.clearCachedCredentials()` in addition to calling `.logout()`. This keeps the API simpler/purer (each method does one thing), but it does mean that clients would need to understand what they're doing to avoid unintended credential retention.

**Comment by ryscheng** [comment]
This seems reasonable to me
:+1:

**Comment by soycode** [comment]
Went ahead and merged since I believe it's the API we want and since you said it won't affect uProxy - if you still have objections though let me know and I can revert/change. Thanks!

**Pull request merged**
